.\" Copyright (c) 2017 Yon <anaseto@bardinflor.perso.aquilenet.fr>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.Dd Jun 12, 2017
.Dt MORJI 1
.Os
.Sh NAME
.Nm morji
.Nd simple flashcard program
.Sh SYNOPSIS
.Nm
.Op Fl c Ar config-file
.Op Fl f Ar dbfile
.Op Fl x Ar script
.Sh DESCRIPTION
.Nm
is a simple flashcard program for the terminal.
It uses a modified version of the SM2 algorithm to schedule cards for review.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl c Ar config-file
Specify a custom config file location.
.It Fl f Ar dbfile
Specify a custom database file location.
.It Fl x Ar script
Execute a Tcl script to perform operations on the database with access to
functions in the
.Pa morji::
namespace.
.Em Note:
interface is subject to change.
.El
.Pp
Help on key-bindings is available from within the user interface.
.Pp
Actions that ask to select or deselect tags use glob pattern matching:
in particular
.Sq *
can be used to mean “any sequence of characters”.
The find action uses glob pattern matching too, but
.Sq *
is implicitly added at the start and at the end of the pattern.
.Sh FILES
.Bl -tag -width Ds -compact
.It Pa "$XDG_CONFIG_HOME/morji/init.tcl"
The default initialization script path.
See
.Xr morji_config 5
for the syntax of this file.
If the variable
.Ev XDG_CONFIG_HOME
is not defined, the path
.Pa ~/.config/
is used instead.
.It Pa "$XDG_DATA_HOME/morji/morji.db"
The default database path.
If the variable
.Ev XDG_DATA_HOME
is not defined, the path
.Pa ~/.local/share/
is used instead.
.El
.Sh SEE ALSO
.Xr morji_config 5 ,
.Xr morji_facts 5
